#!/usr/bin/env python
"""
    Scan through IEEE802.11 (WLAN) channels on a specific interface
    
    @author: Jean-Lou Dupont
"""
__version__="0.1"
import os, sys, argparse
op=os.path

try:
    import jldcmds #@UnusedImport
except:
    ### must be in dev mode then    
    this_dir=op.dirname(__file__)
    lib_path=op.abspath(op.join(this_dir, ".."))
    sys.path.insert(0, lib_path)
    import jldcmds #@UnusedImport

########################################################################

DESC="Scan WLAN channels - version %s" % __version__

DEFAULT_PATTERN = "1:3 2:5 6:3 3:5 11:3 4:5 1:3 5:5 6:3 7:5 11:3 8:5 1:3 9:5 6:3 10:5 11:3 12:5 1:3 13:5 6:3 14:5"

def main():
    try:
        import jldcmds.common.do_setup #@UnusedImport
        import logging
        import jldcmds.do_checks      #@UnusedImport
        
        parser=argparse.ArgumentParser(description=DESC, fromfile_prefix_chars='@')
        parser.add_argument('-d',  dest='debug', action='store_true', help="Debug Mode", default=False)
        
        parser.add_argument('-iface',    dest='iface',     type=str, help="Interface name",     default="wlan0")
        parser.add_argument('-p',        dest='pattern',   type=str, help="Pattern Definition", nargs="+", default = DEFAULT_PATTERN)
        
        args=parser.parse_args()
        
        from jldcmds.common.tools_sys import dnorm, info_dump
        from jldcmds.script_wscan import run
        
        args=dnorm(vars(args))
        
        if args.get('debug', False):
            info_dump(args, 20)
                   
        run(**args)


    except KeyboardInterrupt:
        logging.info("... exiting")
        sys.exit(0)##no probs
        
    except Exception,e:
        logging.error(str(e))
        sys.exit(1)
        

sys.exit(main())
