'''
    Created on Mar 14, 2015
    @author: jldupont
'''

WLAN_FRAME_TYPE_MANAGEMENT = 0
WLAN_FRAME_SUBTYPE_PROBE_REQUEST = 4
WLAN_FRAME_SUBTYPE_PROBE_RESPONSE = 5
WLAN_FRAME_SUBTYPE_BEACON = 8

WLAN_BEACON_ELEMENT_SSID = 0